apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sbapp
  labels:
    app: sbapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sbapp
  template:
    metadata:
      labels:
        app: sbapp
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP